// @ts-nocheck
// Dutch nouns with their articles (het = neuter, de = common gender)
// Based on frequency analysis of Dutch language - ~800 words

export const dutchWords: Record<string, "het" | "de" | "both"> = {
  // ===== HET WORDS (Neuter) =====

  // Diminutives (always het)
  meisje: "het",
  jongetje: "het",
  kindje: "het",
  huisje: "het",
  boekje: "het",
  bloemetje: "het",
  hondje: "het",
  katje: "het",
  vogeltje: "het",
  kopje: "het",
  broekje: "het",
  jurkje: "het",
  schoentje: "het",
  autootje: "het",
  beetje: "het",

  // Words ending in -um (Latin origin)
  museum: "het",
  centrum: "het",
  stadium: "het",
  gymnasium: "het",
  aquarium: "het",
  laboratorium: "het",
  auditorium: "het",
  crematorium: "het",
  moratorium: "het",
  planetarium: "het",
  referendum: "het",
  symposium: "het",
  curriculum: "het",
  podium: "het",
  medium: "het",
  premium: "het",
  album: "het",
  forum: "het",
  minimum: "het",
  maximum: "het",
  optimum: "het",

  // Words ending in -ment
  moment: "het",
  document: "het",
  instrument: "het",
  experiment: "het",
  fragment: "het",
  argument: "het",
  element: "het",
  monument: "het",
  supplement: "het",
  complement: "het",
  compartiment: "het",
  regiment: "het",
  appartement: "het",
  parlement: "het",
  sentiment: "het",
  testament: "het",

  // Words ending in -isme
  socialisme: "het",
  kapitalisme: "het",
  communisme: "het",
  liberalisme: "het",
  nationalisme: "het",
  racisme: "het",
  terrorisme: "het",
  toerisme: "het",
  optimisme: "het",
  pessimisme: "het",
  realisme: "het",
  idealisme: "het",
  materialisme: "het",
  atheisme: "het",
  katholicisme: "het",
  protestantisme: "het",
  judaisme: "het",
  boeddhisme: "het",
  hindoeisme: "het",
  feminisme: "het",
  seksisme: "het",
  vandalisme: "het",
  alcoholisme: "het",
  fanatisme: "het",
  egoisme: "het",
  cynisme: "het",

  // Words ending in -sel
  voedsel: "het",
  raadsel: "het",
  deksel: "het",
  mengsel: "het",
  baksel: "het",
  brouwsel: "het",
  maaksel: "het",
  kooksel: "het",
  bouwsel: "het",

  // Infinitives used as nouns
  eten: "het",
  drinken: "het",
  leven: "het",
  lopen: "het",
  rijden: "het",
  zwemmen: "het",
  slapen: "het",
  werken: "het",
  lezen: "het",
  schrijven: "het",
  spreken: "het",
  zingen: "het",
  dansen: "het",
  koken: "het",
  fietsen: "het",
  voetballen: "het",
  tennissen: "het",

  // Common het words - Body parts
  hoofd: "het",
  haar: "het",
  oog: "het",
  oor: "het",
  been: "het",
  hart: "het",
  lichaam: "het",
  gezicht: "het",
  brein: "het",
  gebit: "het",

  // Common het words - Food and drink
  brood: "het",
  water: "het",
  bier: "het",
  fruit: "het",
  vlees: "het",
  ei: "het",
  ijs: "het",
  zout: "het",
  vet: "het",
  meel: "het",
  deeg: "het",
  gebak: "het",
  ontbijt: "het",
  diner: "het",

  // Common het words - House and furniture
  huis: "het",
  bed: "het",
  raam: "het",
  dak: "het",
  plafond: "het",
  toilet: "het",
  bad: "het",
  behang: "het",
  tapijt: "het",
  gordijn: "het",
  kussen: "het",
  laken: "het",
  dekbed: "het",

  // Common het words - Nature
  gras: "het",
  blad: "het",
  bos: "het",
  strand: "het",
  zand: "het",
  mos: "het",
  riet: "het",
  onweer: "het",
  weer: "het",
  klimaat: "het",
  landschap: "het",
  eiland: "het",

  // Common het words - Abstract concepts
  geluk: "het",
  gevoel: "het",
  idee: "het",
  probleem: "het",
  systeem: "het",
  doel: "het",
  begin: "het",
  einde: "het",
  werk: "het",
  geld: "het",
  recht: "het",
  geweld: "het",
  gedrag: "het",
  geloof: "het",
  vertrouwen: "het",
  respect: "het",
  succes: "het",
  effect: "het",
  resultaat: "het",
  verschil: "het",
  voorbeeld: "het",
  antwoord: "het",
  verhaal: "het",
  gesprek: "het",
  nieuws: "het",
  bericht: "het",
  voorstel: "het",
  besluit: "het",
  advies: "het",
  bewijs: "het",
  geheim: "het",

  // Common het words - Places
  land: "het",
  park: "het",
  station: "het",
  kantoor: "het",
  gebouw: "het",
  hotel: "het",
  restaurant: "het",
  cafe: "het",
  theater: "het",
  ziekenhuis: "het",
  postkantoor: "het",
  vliegveld: "het",

  // Common het words - Objects
  boek: "het",
  glas: "het",
  mes: "het",
  bord: "het",
  papier: "het",
  nummer: "het",
  artikel: "het",
  woord: "het",
  beeld: "het",
  schilderij: "het",
  portret: "het",
  spel: "het",
  speelgoed: "het",
  gereedschap: "het",
  wapen: "het",
  schip: "het",
  vliegtuig: "het",
  voertuig: "het",

  // Common het words - Technology
  internet: "het",
  programma: "het",
  toetsenbord: "het",
  scherm: "het",
  netwerk: "het",
  apparaat: "het",

  // Common het words - Time
  jaar: "het",
  seizoen: "het",
  weekend: "het",
  tijdstip: "het",
  verleden: "het",
  heden: "het",
  uur: "het",

  // Words with ge- prefix (often het)
  gebrek: "het",
  gebied: "het",
  geval: "het",
  gevaar: "het",
  gebruik: "het",
  gezag: "het",
  gezelschap: "het",
  geluid: "het",
  gewicht: "het",
  gemak: "het",
  geduld: "het",
  geheel: "het",
  gezin: "het",

  // Additional het words
  kind: "het",
  percentage: "het",
  onderwerp: "het",
  bedrijf: "het",
  karakter: "het",
  principe: "het",
  concept: "het",
  project: "het",
  product: "het",
  proces: "het",
  model: "het",
  niveau: "het",
  volume: "het",
  contact: "het",
  contract: "het",
  ticket: "het",
  budget: "het",
  talent: "het",
  comfort: "het",
  accent: "het",
  aspect: "het",
  object: "het",
  subject: "het",
  dialect: "het",
  feit: "het",
  detail: "het",
  festival: "het",
  signaal: "het",
  materiaal: "het",
  kapitaal: "het",
  potentieel: "het",
  orgaan: "het",
  bestaan: "het",
  paard: "het",
  varken: "het",
  schaap: "het",
  konijn: "het",
  shirt: "het",
  hemd: "het",

  // ===== DE WORDS (Common Gender) =====

  // People and professions
  man: "de",
  vrouw: "de",
  jongen: "de",
  baby: "de",
  persoon: "de",
  mens: "de",
  dokter: "de",
  arts: "de",
  leraar: "de",
  lerares: "de",
  student: "de",
  professor: "de",
  advocaat: "de",
  rechter: "de",
  politieagent: "de",
  soldaat: "de",
  koning: "de",
  koningin: "de",
  president: "de",
  minister: "de",
  directeur: "de",
  manager: "de",
  baas: "de",
  werknemer: "de",
  collega: "de",
  klant: "de",
  gast: "de",
  vriend: "de",
  vriendin: "de",
  buurman: "de",
  buurvrouw: "de",

  // Family members
  moeder: "de",
  vader: "de",
  ouder: "de",
  broer: "de",
  zus: "de",
  zoon: "de",
  dochter: "de",
  oom: "de",
  tante: "de",
  neef: "de",
  nicht: "de",
  opa: "de",
  oma: "de",
  grootvader: "de",
  grootmoeder: "de",
  schoonmoeder: "de",
  schoonvader: "de",

  // Animals
  hond: "de",
  kat: "de",
  vogel: "de",
  vis: "de",
  koe: "de",
  kip: "de",
  eend: "de",
  gans: "de",
  muis: "de",
  rat: "de",
  spin: "de",
  vlinder: "de",
  bij: "de",
  wesp: "de",
  mier: "de",
  vlieg: "de",
  mug: "de",
  leeuw: "de",
  tijger: "de",
  beer: "de",
  wolf: "de",
  vos: "de",
  aap: "de",
  olifant: "de",
  slang: "de",
  schildpad: "de",
  kikker: "de",

  // Body parts (de words)
  hand: "de",
  voet: "de",
  arm: "de",
  neus: "de",
  mond: "de",
  tong: "de",
  lip: "de",
  tand: "de",
  vinger: "de",
  teen: "de",
  knie: "de",
  elleboog: "de",
  schouder: "de",
  rug: "de",
  buik: "de",
  borst: "de",
  hals: "de",
  nek: "de",
  kin: "de",
  wang: "de",

  // Clothing
  jas: "de",
  broek: "de",
  rok: "de",
  jurk: "de",
  trui: "de",
  schoen: "de",
  laars: "de",
  sok: "de",
  handschoen: "de",
  sjaal: "de",
  hoed: "de",
  pet: "de",
  muts: "de",
  das: "de",
  riem: "de",
  tas: "de",
  portemonnee: "de",

  // Time words
  dag: "de",
  nacht: "de",
  week: "de",
  maand: "de",
  tijd: "de",
  minuut: "de",
  seconde: "de",
  ochtend: "de",
  middag: "de",
  avond: "de",
  morgen: "de",

  // Days of the week
  maandag: "de",
  dinsdag: "de",
  woensdag: "de",
  donderdag: "de",
  vrijdag: "de",
  zaterdag: "de",
  zondag: "de",

  // Months
  januari: "de",
  februari: "de",
  maart: "de",
  april: "de",
  mei: "de",
  juni: "de",
  juli: "de",
  augustus: "de",
  september: "de",
  oktober: "de",
  november: "de",
  december: "de",

  // Seasons
  lente: "de",
  zomer: "de",
  herfst: "de",
  winter: "de",

  // Places and buildings
  stad: "de",
  straat: "de",
  weg: "de",
  brug: "de",
  tunnel: "de",
  hoek: "de",
  buurt: "de",
  wijk: "de",
  gemeente: "de",
  provincie: "de",
  regio: "de",
  grens: "de",
  school: "de",
  universiteit: "de",
  kerk: "de",
  moskee: "de",
  synagoge: "de",
  tempel: "de",
  winkel: "de",
  supermarkt: "de",
  markt: "de",
  bank: "de",
  bibliotheek: "de",
  bioscoop: "de",
  disco: "de",
  fabriek: "de",

  // House and rooms
  kamer: "de",
  keuken: "de",
  badkamer: "de",
  slaapkamer: "de",
  woonkamer: "de",
  zolder: "de",
  kelder: "de",
  garage: "de",
  tuin: "de",
  deur: "de",
  muur: "de",
  vloer: "de",
  trap: "de",

  // Furniture
  tafel: "de",
  stoel: "de",
  kast: "de",
  lamp: "de",
  klok: "de",
  spiegel: "de",

  // Transportation
  auto: "de",
  fiets: "de",
  trein: "de",
  bus: "de",
  tram: "de",
  metro: "de",
  taxi: "de",
  boot: "de",
  motor: "de",
  bromfiets: "de",
  scooter: "de",

  // Nature
  boom: "de",
  bloem: "de",
  plant: "de",
  struik: "de",
  zon: "de",
  maan: "de",
  ster: "de",
  wolk: "de",
  lucht: "de",
  wind: "de",
  regen: "de",
  sneeuw: "de",
  hagel: "de",
  zee: "de",
  oceaan: "de",
  rivier: "de",
  beek: "de",
  vijver: "de",
  berg: "de",
  heuvel: "de",
  vallei: "de",
  woestijn: "de",

  // Food and kitchen
  maaltijd: "de",
  lunch: "de",
  soep: "de",
  salade: "de",
  pizza: "de",
  pasta: "de",
  rijst: "de",
  aardappel: "de",
  groente: "de",
  tomaat: "de",
  ui: "de",
  wortel: "de",
  kool: "de",
  sla: "de",
  appel: "de",
  peer: "de",
  banaan: "de",
  sinaasappel: "de",
  citroen: "de",
  druif: "de",
  aardbei: "de",
  kers: "de",
  kaas: "de",
  boter: "de",
  melk: "de",
  koffie: "de",
  thee: "de",
  wijn: "de",
  limonade: "de",
  saus: "de",
  suiker: "de",

  // Kitchen items
  pan: "de",
  pot: "de",
  lepel: "de",
  vork: "de",
  kop: "de",
  fles: "de",
  schaal: "de",

  // Technology and media
  computer: "de",
  laptop: "de",
  tablet: "de",
  telefoon: "de",
  televisie: "de",
  radio: "de",
  camera: "de",
  printer: "de",
  website: "de",
  app: "de",
  foto: "de",
  video: "de",
  film: "de",
  serie: "de",

  // Communication and documents
  krant: "de",
  brief: "de",
  kaart: "de",
  envelop: "de",
  folder: "de",
  brochure: "de",
  agenda: "de",
  lijst: "de",
  nota: "de",
  rekening: "de",
  factuur: "de",
  bon: "de",

  // Music and art
  muziek: "de",
  kunst: "de",
  gitaar: "de",
  piano: "de",
  viool: "de",
  trompet: "de",
  drum: "de",
  fluit: "de",
  tekening: "de",
  sculptuur: "de",

  // Sports and games
  sport: "de",
  voetbal: "de",
  bal: "de",
  wedstrijd: "de",
  race: "de",
  marathon: "de",

  // Abstract concepts (de words)
  vraag: "de",
  reden: "de",
  oorzaak: "de",
  oplossing: "de",
  mogelijkheid: "de",
  kans: "de",
  keuze: "de",
  beslissing: "de",
  mening: "de",
  gedachte: "de",
  herinnering: "de",
  ervaring: "de",
  kennis: "de",
  informatie: "de",
  waarheid: "de",
  leugen: "de",
  fout: "de",
  vergissing: "de",
  verandering: "de",
  ontwikkeling: "de",
  vooruitgang: "de",
  groei: "de",
  situatie: "de",
  omstandigheid: "de",
  toestand: "de",
  staat: "de",
  wet: "de",
  regel: "de",
  orde: "de",
  vrijheid: "de",
  vrede: "de",
  oorlog: "de",
  strijd: "de",
  overwinning: "de",
  nederlaag: "de",
  macht: "de",
  kracht: "de",
  energie: "de",
  waarde: "de",
  prijs: "de",
  kosten: "de",
  belasting: "de",
  schuld: "de",
  winst: "de",
  verlies: "de",

  // Words ending in -heid (always de)
  gezondheid: "de",
  ziekte: "de",
  eenheid: "de",
  veiligheid: "de",
  zekerheid: "de",
  werkelijkheid: "de",
  gelegenheid: "de",
  moeilijkheid: "de",
  snelheid: "de",
  persoonlijkheid: "de",
  schoonheid: "de",
  lelijkheid: "de",
  goedheid: "de",
  slechtheid: "de",
  rijkdom: "de",
  armoede: "de",

  // Words ending in -ing (always de)
  vergadering: "de",
  regering: "de",
  bevolking: "de",
  beweging: "de",
  richting: "de",
  betekenis: "de",
  bedoeling: "de",
  voorstelling: "de",
  uitvoering: "de",
  opleiding: "de",
  training: "de",
  verbetering: "de",
  vermindering: "de",
  uitbreiding: "de",
  inleiding: "de",
  afdeling: "de",
  woning: "de",
  omgeving: "de",
  opening: "de",
  sluiting: "de",
  inrichting: "de",

  // Words ending in -tie/-sie (always de)
  organisatie: "de",
  communicatie: "de",
  relatie: "de",
  reactie: "de",
  actie: "de",
  productie: "de",
  constructie: "de",
  instructie: "de",
  functie: "de",
  positie: "de",
  conditie: "de",
  traditie: "de",
  definitie: "de",
  editie: "de",
  competitie: "de",
  repetitie: "de",
  presentatie: "de",
  demonstratie: "de",
  operatie: "de",
  generatie: "de",
  populatie: "de",
  natie: "de",
  emotie: "de",
  discussie: "de",
  sessie: "de",
  commissie: "de",
  missie: "de",
  versie: "de",
  pensie: "de",
  passie: "de",

  // Words ending in -schap
  maatschappij: "de",
  wetenschap: "de",
  vriendschap: "de",

  // Words ending in -teit (always de)
  kwaliteit: "de",
  kwantiteit: "de",
  capaciteit: "de",
  elektriciteit: "de",
  activiteit: "de",
  identiteit: "de",
  nationaliteit: "de",
  realiteit: "de",
  populariteit: "de",

  // Colors and misc
  kleur: "de",
  plaats: "de",
  ruimte: "de",
  afstand: "de",
  lengte: "de",
  breedte: "de",
  hoogte: "de",
  diepte: "de",
  grootte: "de",
  maat: "de",
  vorm: "de",
  kant: "de",
  zijde: "de",
  lijn: "de",
  cirkel: "de",
  driehoek: "de",
  punt: "de",
  stip: "de",
  plek: "de",
  naam: "de",
  titel: "de",
  taal: "de",
  stem: "de",
  boodschap: "de",
  tekst: "de",
  zin: "de",
  letter: "de",
  handtekening: "de",
  familie: "de",
  les: "de",
  klas: "de",
  politie: "de",

  // ===== WORDS THAT CAN BE BOTH =====
  blog: "both",
  email: "both",
  sms: "both",
  wifi: "both",
};

export default dutchWords;
